(async function(){
  'use strict';
  const client=window.supabase&&window.supabase.createClient?window.supabase.createClient('https://uzitnphltzblfccmiecf.supabase.co','sb_publishable_8_3FrRYH5JSpdpi9sSv9Wg_T2ST8IGW'):null;
  const $=id=>document.getElementById(id); const status=$('course-status'),title=$('course-title'),desc=$('course-description'),feedback=$('course-feedback');
  function setState(label,message){status.textContent=label;feedback.textContent=message||''}
  function renderMaterials(modules,completed){const target=$('materials-list');target.replaceChildren();if(!modules.length){target.innerHTML='<div class="course-empty">Ainda não existem módulos publicados para este curso.</div>';return}modules.slice().reverse().forEach(m=>{const card=document.createElement('div');card.className='material-item';card.innerHTML='<strong></strong><span></span>';card.querySelector('strong').textContent=m.titulo||'Módulo';card.querySelector('span').textContent=completed.includes(m.id)?'Concluído':'Material de estudo';target.appendChild(card)})}
  if(!client){setState('Erro','Não foi possível ligar ao serviço de cursos.');return}
  const {data:{user}}=await client.auth.getUser();if(!user){window.location.href='login.html?redirect=meu-curso.html';return}
  const displayName=(user.user_metadata&&(user.user_metadata.full_name||user.user_metadata.name))||(user.email?user.email.split('@')[0]:'aluno');
  const result=await client.from('inscricoes').select('curso_id,estado,created_at,cursos(id,nome,descricao)').eq('user_id',user.id).order('created_at',{ascending:false});
  if(result.error){setState('Erro','Não foi possível carregar as tuas inscrições.');title.textContent='Erro ao carregar o curso';desc.textContent='Tenta atualizar a página.';return}
  const entries=result.data||[],confirmed=entries.filter(x=>x.estado==='confirmado'),pending=entries.filter(x=>x.estado!=='confirmado'),current=confirmed[0];
  if(!current){setState(pending.length?'Pendente':'Sem inscrição',pending.length?'A tua inscrição está pendente de aprovação.':'Ainda não tens uma inscrição confirmada.');title.textContent='Ainda não tens um curso inscrito';desc.textContent='Consulta o catálogo completo para escolheres uma formação.';$('next-module').textContent='Escolhe uma formação';$('next-state').textContent='Todos os cursos disponíveis estão listados no catálogo Nurse.';return}
  const course=current.cursos||{};setState('Confirmado','Inscrição confirmada.');title.textContent=course.nome||'Curso inscrito';desc.textContent=course.descricao||'Os teus módulos e materiais estão disponíveis abaixo.';
  const modulesResult=await client.from('modulos').select('id,titulo,ordem,descricao').eq('curso_id',current.curso_id).order('ordem',{ascending:true});const modules=modulesResult.data||[];
  const progressResult=await client.from('progresso_modulos').select('modulo_id,estado').eq('curso_id',current.curso_id).eq('user_id',user.id);const completed=(progressResult.data||[]).filter(x=>x.estado==='concluido').map(x=>x.modulo_id);const percent=modules.length?Math.round(completed.length/modules.length*100):0;
  $('progress-percent').textContent=percent+'%';$('progress-bar').style.width=percent+'%';$('progress-summary').textContent=modules.length?completed.length+' de '+modules.length+' módulos concluídos':'Ainda não existem módulos publicados.';const next=modules.find(m=>!completed.includes(m.id));$('next-module').textContent=next?next.titulo:'Curso concluído';$('next-state').textContent=next?(completed.length?'Continua a partir do próximo módulo.':'Começa pelo primeiro módulo.'):'Parabéns por concluíres todos os módulos.';renderMaterials(modules,completed);
  const others=confirmed.slice(1).concat(pending),otherTarget=$('other-enrollments');if(others.length){otherTarget.innerHTML='<p class="eyebrow" style="margin-top:28px">Outras inscrições</p>';others.forEach(item=>{const row=document.createElement('div');row.className='course-option';const c=item.cursos||{};row.innerHTML='<div><strong></strong><span></span></div>';row.querySelector('strong').textContent=c.nome||'Curso';row.querySelector('span').textContent=item.estado==='confirmado'?'Confirmado':'Pendente';otherTarget.appendChild(row)})}
})();
